// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmuuncsotulgbwhckujd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtdXVuY3NvdHVsZ2J3aGNrdWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDcxODYsImV4cCI6MjA2NTEyMzE4Nn0.HY-ruqsqnScw9oWkjQZ_m58W5hYmvrsu_mxggYbnTHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);